/**
 * Generates supabase/seed/dailies.sql: one puzzle per mode per day, a year out.
 *
 *   npm run build:dailies              # starts today (UTC)
 *   npm run build:dailies -- 2026-01-01 400
 *
 * Deterministic, so re-running for the same start date produces byte-identical
 * SQL. Extending the window later is just a re-run with a larger day count --
 * already-played dates keep their answers because pickDaily depends only on the
 * date, the mode, and the answers that came before it.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CLASSIC_POOL, FULL_POOL } from '../src/data/pools.js'
import { pickDaily, todayUTC, type DailyMode } from '../src/game/daily.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const NL = String.fromCharCode(10)

const args = process.argv.slice(2).filter((a) => !a.startsWith('-'))
const START = args[0] ?? todayUTC()
const DAYS = Number(args[1] ?? 365)

if (!/^\d{4}-\d{2}-\d{2}$/.test(START)) {
  console.error(`Bad start date: ${START}. Expected YYYY-MM-DD.`)
  process.exit(1)
}

const MODES: { mode: DailyMode; pool: typeof CLASSIC_POOL }[] = [
  { mode: 'classic', pool: CLASSIC_POOL },
  { mode: 'full', pool: FULL_POOL },
]

const rows: string[] = []
const startMs = Date.parse(`${START}T00:00:00Z`)

for (const { mode, pool } of MODES) {
  const history: { date: string; characterId: string }[] = []
  for (let d = 0; d < DAYS; d++) {
    const date = new Date(startMs + d * 86_400_000).toISOString().slice(0, 10)
    const pick = pickDaily(date, mode, pool, history)
    history.push({ date, characterId: pick.id })
    rows.push(`  ('${date}', '${mode}', '${pick.id}')`)
  }

  const distinct = new Set(history.map((h) => h.characterId)).size
  console.log(
    `${mode.padEnd(8)} ${DAYS} days from ${START}: ${distinct} distinct characters of ${pool.length} available`,
  )
}

const sql = [
  '-- Generated by scripts/seed-dailies.ts -- do not edit.',
  `-- ${DAYS} days per mode from ${START}. Run after seed/characters.sql.`,
  '-- Re-runnable: existing dates keep their answer, so a player mid-streak is',
  '-- unaffected by extending the window.',
  '',
  'insert into public.daily_puzzles (puzzle_date, mode, character_id) values',
  rows.join(',' + NL) + '',
  'on conflict (puzzle_date, mode) do nothing;',
  '',
].join(NL)

const out = join(ROOT, 'supabase', 'seed', 'dailies.sql')
await mkdir(dirname(out), { recursive: true })
await writeFile(out, sql)
console.log(`Wrote ${out} (${rows.length} puzzles)`)
